//
// Copyright (c) 2018, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: kubernetes-microprofile-config
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2018-10-12
:page-description: Externalize configuration and use Kubernetes ConfigMaps and Secretes to configure your microservices.
:page-tags: ['Kubernetes', 'Docker', 'MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro', 'microprofile-config', 'cdi-intro', 'docker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: MicroProfile Configuration in Kubernetes tutorial
:page-seo-description: How to externalize configuration with Eclipse MicroProfile Configuration and use Kubernetes ConfigMaps and Secrets to configure your microservices
:guide-author: Open Liberty
= Configuring microservices running in Kubernetes

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to externalize configuration using MicroProfile Config and configure your microservices using Kubernetes ConfigMaps and Secrets.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:system-api: http://[hostname]:31000/system/properties
:inventory-api: http://[hostname]:32000/inventory/systems
:win: Windows
:mac: Mac
:linux: Linux

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how and why to externalize your microservice's configuration. Externalized configuration is useful because configuration usually changes depending on your environment. You will also learn how to configure the environment by providing required values to your application using {kube}. Using environment variables allows for easier deployment to different environments.

MicroProfile Config provides useful annotations that you can use to inject configured values into your code. These values can come from any config sources, such as environment variables. To learn more about MicroProfile Config, read the https://openliberty.io/guides/microprofile-config.html[Configuring microservices^] guide.

Furthermore, you'll learn how to set these environment variables with ConfigMaps and Secrets. These resources are provided by {kube} and act as a data source for your environment variables. You can use a ConfigMap or Secret to set environment variables for any number of containers.

// =================================================================================================
// Prerequisites
// =================================================================================================
[role='command']
include::{common-includes}/kube-prereq.adoc[]

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Starting/Preparing Cluster
// =================================================================================================
[role='command']
include::{common-includes}/kube-start.adoc[]

== Deploying the microservices

The two microservices you will deploy are called `system` and `inventory`. The `system` microservice
returns the JVM system properties of the running container and it returns the pod's name in the HTTP header
making replicas easy to distinguish from each other. The `inventory` microservice
adds the properties from the `system` microservice to the inventory. This demonstrates
how communication can be established between pods inside a cluster.
To build these applications, navigate to the `start` directory and run the following command.

[role='command']
```
mvn clean package
```

When the build succeeds, run the following command to deploy the necessary {kube} resources to serve the applications.
[role='command']
```
kubectl apply -f kubernetes.yaml
```

When this command finishes, wait for the pods to be in the Ready state. Run the following command to view the status of the pods.
[role='command']
```
kubectl get pods
```

When the pods are ready, the output shows `1/1` for READY and `Running` for STATUS.

[source, role="no_copy"]
----
NAME                                   READY     STATUS    RESTARTS   AGE
system-deployment-6bd97d9bf6-6d2cj     1/1       Running   0          34s
inventory-deployment-645767664f-7gnxf  1/1       Running   0          34s
----

After the pods are ready, you will make requests to your services.

****
[system]#*{win} | {mac}*#

The default host name for Docker Desktop is `localhost`.

[system]#*{linux}*#

The default host name for minikube is {minikube-ip}. Otherwise it can be found using the `minikube ip` command.
****

Navigate to `{system-api}` and use the user name `bob` and the password `bobpwd` to authenticate. Replace `[hostname]` with the IP address or host name of your {kube} cluster. Open your browser's developer console and examine the response headers. Observe that the `X-App-Name` header currently has the value `system`.

Similarly, navigate to `{inventory-api}/system-service` and the system will be added to your inventory.

== Modifying system microservice

The `system` service is hardcoded to have `system` as the app name. You'll make this name configurable by adding the `appName` member and `X-App-Name` header.

[role="code_command hotspot", subs="quotes"]
----
#Replace the `SystemResource` class.#
`system/src/main/java/io/openliberty/guides/system/SystemResource.java`
----

SystemResource.java
[source, java, linenums, role='code_column']
----
include::finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java[tags=**;!copyright;]
----
The [hotspot=21]`appName` member was added to the [hotspot=32]`header` value in [hotspot=29-34]`getProperties()`.

These changes use MicroProfile Config and CDI to inject the value of an environment variable called [hotspot=20]`APP_NAME` into the [hotspot=21]`appName` member of the `SystemResource` class.

== Modifying inventory microservice

The `inventory` service is hardcoded to use `bob` and `bobpwd` as the credentials to authenticate against the `system` service. You'll make these credentials configurable. 

[role="code_command hotspot", subs="quotes"]
----
#Replace the `SystemClient` class.#
`inventory/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java`
----

SystemClient.java
[source, java, linenums, role='code_column']
----
include::finish/inventory/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=**;!copyright;]
----

The changes introduced here use MicroProfile Config and CDI to inject the value of the environment variables [hotspot=28-30]`SYSTEM_APP_USERNAME` and [hotspot=32-34]`SYSTEM_APP_PASSWORD` into the `SystemClient` class.


== Creating a ConfigMap and Secret

There are several ways to configure an environment variable in a Docker container. You can set it directly in the [hotspot file=1]`Dockerfile` with the `ENV` command. You can also set it in your [hotspot file=0]`kubernetes.yaml` file by specifying a name and a value for the environment variable you want to set for a specific container. With these options in mind, you're going to use a ConfigMap and Secret to set these values. These are resources provided by Kubernetes that are used as a way to provide configuration values to your containers. A benefit is that they can be reused across many different containers, even if they all require different environment variables to be set with the same value.

Create a ConfigMap to configure the app name with the following `kubectl` command.
[role='command']
```
kubectl create configmap sys-app-name --from-literal name=my-system
```

This command deploys a ConfigMap named `sys-app-name` to your cluster. It has a key called `name` with a value of `my-system`. The `--from-literal` flag allows you to specify individual key-value pairs to store in this ConfigMap. Other available options, such as `--from-file` and `--from-env-file`, provide more versatility as to what you want to configure. Details about these options can be found in the https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-configmap-em-[{kube} CLI documentation^].

Create a Secret to configure the credentials that `inventory` will use to authenticate against `system` with the following `kubectl` command.
[role='command']
```
kubectl create secret generic sys-app-credentials --from-literal username=bob --from-literal password=bobpwd
```
 
This command looks very similar to the command to create a ConfigMap, one difference is the word `generic`. It means you're creating a Secret that is `generic`, in other words it stores information that isn't specialized in any way. There are different types of secrets, such as secrets to store Docker credentials and secrets to store public and private key pairs.

A Secret is similar to a ConfigMap. A key difference is that a Secret is used for confidential information such as credentials. One of the main differences is that you must explicitly tell `kubectl` to show you the contents of a Secret. Additionally, when it does show you the information, it only shows you a Base64 encoded version so that a casual onlooker doesn't accidentally see any sensitive data. Secrets don't provide any encryption by default, that is something you'll either need to do yourself or find an alternate option to configure.

kubernetes.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/kubernetes.yaml[]
----

Dockerfile
[source, text, linenums, role='code_column']
----
include::finish/system/Dockerfile[]
----

== Updating {kube} resources

Next, you will update your {kube} deployments to set the environment variables in your containers based on the values configured in the ConfigMap and Secret created previously. 
The [hotspot=22-27]`env` section under the [hotspot=17-27]`system-container` is where the [hotspot=23-27]`APP_NAME` environment variable will be set.
The [hotspot=50-60]`env` section under the [hotspot=45-60]`inventory-container` is where the [hotspot=51-55]`SYSTEM_APP_USERNAME` and [hotspot=56-60]`SYSTEM_APP_PASSWORD` environment variables will be set.

[role="code_command hotspot", subs="quotes"]
----
#Replace the kubernetes file.#
`kubernetes.yaml`
----

kubernetes.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/kubernetes.yaml[]
----

In the [hotspot]`kubernetes.yaml` file where the containers are defined, you can see the [hotspot=24-27 hotspot=52-55 hotspot=57-60]`valueFrom` field that allows you to specify the value of an environment variable from various sources. These sources include a ConfigMap, a Secret, and information about the cluster. In this example [hotspot=25-27]`configMapKeyRef` gets the value [hotspot=27]`name` from the ConfigMap [hotspot=26]`sys-app-name`. Similarly, [hotspot=53-55 hotspot=58-60]`secretKeyRef` gets the values [hotspot=55]`username` and [hotspot=60]`password` from the Secret [hotspot=54 hotspot=59]`sys-app-credentials`.

== Deploying your changes

Rebuild the application using `mvn clean package`.
[role='command']
```
mvn clean package
```

Run the following commands to deploy your changes to the {kube} cluster.
[role='command']
```
kubectl delete -f kubernetes.yaml
kubectl apply -f kubernetes.yaml
```

Navigate to `{system-api}` and examine the response headers in your developer console. You will see that the app name has changed from `system` to `my-system`. Verify that `{inventory-api}/system-service` is working as intended. If it is not, then check the configuration of the credentials.

== Testing the microservices

****
[system]#*{win} | {mac}*#

Run the integration tests against a cluster running with appName `my-system`:
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dsystem.appName=my-system
```

[system]#*{linux}*#

Run the integration tests against a cluster running at Minikube's IP address and with appName `my-system`:
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=`minikube ip` -Dsystem.appName=my-system
```
****


The tests check that the `system` service responds with a header containing the configured name. The tests for `inventory` verify that the service may communicate with `system` using the configured credentials. If the credentials are misconfigured, then the `inventory` test will fail, so the `inventory` test indirectly verifies the credentials are correctly configured.

After the tests succeed, you should see output similar to the following in your console.

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.709 s - in it.io.openliberty.guides.system.SystemEndpointTest

Results:

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.696 s - in it.io.openliberty.guides.inventory.InventoryEndpointTest

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down the environment

Run the following commands to delete all the resources that you created.

[role='command']
```
kubectl delete -f kubernetes.yaml
kubectl delete configmap sys-app-name
kubectl delete secret sys-app-credentials
```

[role='command']
include::{common-includes}/kube-minikube-teardown.adoc[]


// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have used MicroProfile Config to externalize the configuration of two microservices, and then you configured them by creating a ConfigMap and Secret in your {kube} cluster.

// Include the below from the guides-common repo to tell users how they can contribute to the guide

include::{common-includes}/attribution.adoc[subs="attributes"]
