// INSTRUCTION: Please remove all comments that start INSTRUCTION prior to commit. Most comments should be removed, although not the copyright.
// INSTRUCTION: The copyright statement must appear at the top of the file
//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: kubernetes-microprofile-config
:page-layout: guide
:page-duration: 15 minutes
:page-releasedate: 2018-09-24
:page-description: Externalize configuration and use Kubernetes ConfigMaps and Secretes to configure your microservices.
:page-tags: ['microservices', 'Kubernetes', 'Docker', 'containers', 'kubectl', 'Minikube', 'Microprofile', 'mpConfig', 'ConfigMaps', 'Secrets']
:page-permalink: /guides/{projectid}
:page-related-guides: ['docker', 'istio', 'kubernetes']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Configuring microservices with Kubernetes

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to externalize configuration using MicroProfile Config and configure your microservices using Kubernetes ConfigMaps and Secrets.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:name-api: http://[hostname]:31000/api/name
:ping-api: http://[hostname]:32000/api/ping
:win: Windows
:mac: Mac
:linux: Linux

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how and why to externalize your microservice's configuration. Externalized configuration is useful since configuration usually changes depending on your environment. You will also learn how to configure the environment by providing required values to your application using {kube}, this allows for easier deployment to different environments.

By using MicroProfile Config to handle your configuration, it provides useful annotations that you may use to inject configured values into your code. These values can come from any config sources, such as environment variables. If you want to learn more about MicroProfile Config read the https://openliberty.io/guides/microprofile-config.html[Configuring microservices] guide.

Furthermore, you'll learn how to set these environment variables using ConfigMaps and Secrets. These resources are provided by {kube} that act as a data source for your environment variables. By creating a ConfigMap or Secret, they can be used to set environment variables for any number of containers as you see fit.

// =================================================================================================
// Prerequisites
// =================================================================================================

include::{common-includes}/kube-prereq.adoc[]


// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

// =================================================================================================
// Starting/Preparing Cluster
// =================================================================================================

include::{common-includes}/kube-start.adoc[]

== Deploy the name and ping applications

There are two applications that you will deploy -- `name` and `ping`. `name` displays a greeting and displays its container name. `ping` accepts a hostname as a parameter and returns `pong` if it can successfully make a request to `name`, otherwise the request fails. To build these applications, navigate to the `start` directory and run the following command.

```
mvn package
```

When the build succeeds, run the following command to deploy the necessary {kube} resources to serve the applications.

```
kubectl apply -f kubernetes.yaml
```

When this command finishes, wait for the pods to be in the Ready state then navigate to `{name-api}` and use the username `bob` and the password `bobpwd` to authenticate. Replace `[hostname]` with the ip address or hostname of your {kube} cluster. By default it will be `{minikube-ip}` for MiniKube and `localhost` for Docker Desktop. You will see something similar to `Hello! I'm container name-deployment-6bd97d9bf6-qbhbc`.

Similarly, navigate to `{ping-api}/name-service` and you will see `pong`.

== Modify name application

First, update `name` to have a configurable greeting message. At the moment, it is hardcoded to be `Hello!`. Use MicroProfile Config and CDI to inject the value of an environment variable called `GREETING` into the `greeting` member of the `NameResource` class. Then use `greeting` to create a response with a custom greeting message.

Update the name resource class in the `name/src/main/java/io/openliberty/guides/name/NameResource.java` file:
[source, java, indent=0]
----
include::finish/name/src/main/java/io/openliberty/guides/name/NameResource.java[tags=**;!copyright;]
----

== Modify ping application

Update `ping` to make the username and password members configurable. These values are used to authenticate with `name` so they are currently hardcoded to `bob` and `bobpwd` respectively. Now, they will take the values of the environment variables `USERNAME` and `PASSWORD`.

Update the ping resource class in the `ping/src/main/java/io/openliberty/guides/ping/PingResource.java` file:
[source, java, indent=0]
----
include::finish/ping/src/main/java/io/openliberty/guides/ping/PingResource.java[tags=**;!copyright;]
----

== Create ConfigMap and Secret

There are several ways to configure an environment variable in a docker container. You can set it directly in `Dockerfile` by using the `ENV` command. You can also set it in your `kubernetes.yaml` file by specifying a name and a value for the environment variable you want to set for a specific container. With these options in mind, you are going to use a ConfigMap and Secret to set these values. These are resources provided by Kubernetes that are used as a way to provide configuration values to your containers. A benefit is that they can be re-used across many different containers, even if they all require different environment variables to be set with the same value.

Create a ConfigMap to configure the greeting by using the following `kubectl` command.

```
kubectl create configmap greeting-config --from-literal message=Greetings...
```

This command deploys a ConfigMap named `greeting-config` to your cluster. It has a key called `meeting` with a value of `Greetings...`. The `--from-literal` flag allows you to specify individual key-value pairs that you want stored in this ConfigMap. There are other options available such as `--from-file` and `--from-env-file` to allow for more versatility with respect to what you want to configure. More details about these options can be found in the https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-configmap-em-[{kube} CLI Documentation].

Create a Secret to configure the credentials that `ping` will use to authenticate against `name` by using the following `kubectl` command.

```
kubectl create secret generic name-credentials --from-literal username=bob --from-literal password=bobpwd
```

This command looks very similar to the command to create a ConfigMap, one difference is the word `generic`. It means that you're creating a Secret that is `generic`, in other words it stores information that is not specialized in any way. There are different types of secrets, such as secrets to store Docker credentials and a secrets to store public/private key pairs.

A Secret is similar to a ConfigMap, the main difference is that a Secret is used for confidential information such as credentials. One of the main differences is that you have to explicitly tell `kubectl` to show you the contents of a Secret. Additionally, when it does show you the information, it only shows you a Base64 encoded version so that a casual onlooker doesn't accidentally see any sensitive data. They don't provide any encryption by default, that is something you'll either need to do yourself or find an alternate option to configure.

== Update {kube} resources

Next, update your {kube} Deployments in `kubernetes.yaml` to set the environment variables in your containers based on the values configured in the ConfigMap and Secret created previously.

Update the kubernetes resources in the `kubernetes.yaml` file:
[source, java, indent=0]
----
include::finish/kubernetes.yaml[]
----

In the `kubernetes.yaml` file where the containers are defined, you can see the `valueFrom` field which allows you to specify the value of an environment variable from a variety of sources. These sources include a ConfigMap, a Secret, information about the cluster, and the pod's required resources. In this example `configMapKeyRef` is used to get the value `message` from the ConfigMap `greeting-config`. Similarly, `secretKeyRef` is used to get the values `username` and `password` from the Secret `name-credentials`.

== Deploy your changes

Rebuild the application using `mvn package`.

```
mvn package
```

Run the following commands to deploy your changes to the {kube} cluster.

```
kubectl delete -f kubernetes.yaml
kubectl apply -f kubernetes.yaml
```

Navigate to `{name-api}` and you will see that the greeting message has changed from `Hello!` to `Greetings...`. Verify that `{ping-api}/name-service` is working as intended, if it is not then you may have misconfigured the credentials.

== Testing the microservices

Run the tests by running the following command and appropriately substituting `[hostname]` for the correct value.

```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=[hostname]
```

The tests check that `name` responds with a container name, and they check that `ping` responds with `pong` on success and that it gracefully handles a bad response.

Once the tests succeed, you should see output similar to the following in your console.

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.name.NameEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.542 sec - in it.io.openliberty.guides.name.NameEndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.ping.PingEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.761 sec - in it.io.openliberty.guides.ping.PingEndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down the {kube} resources

To remove all of the resources created during this guide, run the following commands to delete all of the resources that you created.

```
kubectl delete -f kubernetes.yaml
kubectl delete configmap greeting-config
kubectl delete secret name-credentials
```

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have used MicroProfile Config to externalize the configuration of two microservices, and then you configured them by creating a ConfigMap and Secret in your {kube} cluster.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
