//
// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: kubernetes-microprofile-config
:page-layout: guide-multipane
:page-duration: 15 minutes
:page-releasedate: 2018-10-12
:page-description: Externalize configuration and use Kubernetes ConfigMaps and Secretes to configure your microservices.
:page-tags: ['Kubernetes', 'Docker', 'MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['kubernetes-intro', 'microprofile-config', 'cdi-intro', 'docker']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: MicroProfile Configuration in Kubernetes tutorial
:page-seo-description: How to externalize configuration with Eclipse MicroProfile Configuration and use Kubernetes ConfigMaps and Secrets to configure your microservices
= Configuring microservices running in Kubernetes

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to externalize configuration using MicroProfile Config and configure your microservices using Kubernetes ConfigMaps and Secrets.

:minikube-ip: 192.168.99.100
:kube: Kubernetes
:name-api: http://[hostname]:31000/api/name
:ping-api: http://[hostname]:32000/api/ping
:win: Windows
:mac: Mac
:linux: Linux

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn
You will learn how and why to externalize your microservice's configuration. Externalized configuration is useful because configuration usually changes depending on your environment. You will also learn how to configure the environment by providing required values to your application using {kube}; this allows for easier deployment to different environments.

MicroProfile Config provides useful annotations that you can use to inject configured values into your code. These values can come from any config sources, such as environment variables. To learn more about MicroProfile Config, read the https://openliberty.io/guides/microprofile-config.html[Configuring microservices] guide.

Furthermore, you'll learn how to set these environment variables with ConfigMaps and Secrets. These resources are provided by {kube} and act as a data source for your environment variables. You can use a ConfigMap or Secret to set environment variables for any number of containers.

// =================================================================================================
// Prerequisites
// =================================================================================================
[role='command']
include::{common-includes}/kube-prereq.adoc[]

// =================================================================================================
// Getting Started
// =================================================================================================
[role='command']
include::{common-includes}/gitclone.adoc[]


// =================================================================================================
// Starting/Preparing Cluster
// =================================================================================================
[role='command']
include::{common-includes}/kube-start.adoc[]

== Deploying the microservices

The two microservices you will deploy are called `name` and `ping`. The `name` microservice displays a brief greeting and the name of the container that it runs in. The `ping` microservice pings the {kube} Service that encapsulates the pod running the `name` microservice. The `ping` microservice demonstrates how communication can be established between pods inside a cluster. To build these applications, navigate to the `start` directory and run the following command.
[role='command']
```
mvn package
```

When the build succeeds, run the following command to deploy the necessary {kube} resources to serve the applications.
[role='command']
```
kubectl apply -f kubernetes.yaml
```

When this command finishes, wait for the pods to be in the Ready state. Run the following command to view the status of the pods.
[role='command']
```
kubectl get pods
```

When the pods are ready, the output shows `1/1` for READY and `Running` for STATUS.

[source, role="no_copy"]
----
NAME                               READY     STATUS    RESTARTS   AGE
name-deployment-6bd97d9bf6-6d2cj   1/1       Running   0          34s
ping-deployment-645767664f-7gnxf   1/1       Running   0          34s
----

After the pods are ready, you will make requests to your services.

****
[system]#*{win} | {mac}*#

The default hostname for Docker Desktop is `localhost`.

[system]#*{linux}*#

The default hostname for minikube is {minikube-ip}. Otherwise it can be found using the `minikube ip` command.
****

Navigate to `{name-api}` and use the username `bob` and the password `bobpwd` to authenticate. Replace `[hostname]` with the IP address or hostname of your {kube} cluster. You will see something similar to `Hello! I'm container name-deployment-6bd97d9bf6-qbhbc`.

Similarly, navigate to `{ping-api}/name-service` and you will see `pong`.

== Modifying name microservice

The `name` service is hardcoded to have `Hello!` as the greeting message. You'll make this message configurable by adding the `greeting` member and return value. 

[role="code_command hotspot=16-18", subs="quotes"]
----
Add the `greeting` member to the `NameResource` class.
`name/src/main/java/io/openliberty/guides/name/NameResource.java`.
----

NameResource.java
[source, java, linenums, role='code_column']
----
include::finish/name/src/main/java/io/openliberty/guides/name/NameResource.java[tags=**;!copyright;]
----
Next, you will add the [hotspot=16-18]`greeting` member to the return value of [hotspot=26-28]`getContainerName()`.

[role="code_command hotspot=27", subs="quotes"]
----
Add the `greeting` member to return value in `getContainerName()`.
`name/src/main/java/io/openliberty/guides/name/NameResource.java`.
----

These changes use MicroProfile Config and CDI to inject the value of an environment variable called [hotspot=17]`GREETING` into the [hotspot=16-18]`greeting` member of the `NameResource` class.

Another change uses the new [hotspot=16-18]`greeting` member to create a response with a custom greeting message in [hotspot=26-28]`getContainerName()`.


== Modifying ping microservice

The `ping` service is hardcoded to use `bob` and `bobpwd` as the credentials to authenticate against the `name` service. You'll make these credentials configurable. 

[role="code_command hotspot=28-34", subs="quotes"]
----
Replace the `username` and `password` variables to the `PingResource` class.
`ping/src/main/java/io/openliberty/guides/ping/PingResource.java`
----

PingResource.java
[source, java, linenums, role='code_column']
----
include::finish/ping/src/main/java/io/openliberty/guides/ping/PingResource.java[tags=**;!copyright;]
----

The changes introduced here use MicroProfile Config and CDI to inject the value of the environment variables [hotspot=28-30]`USERNAME` and [hotspot=32-34]`PASSWORD` into the `PingResource` class.


== Creating a ConfigMap and Secret

There are several ways to configure an environment variable in a Docker container. You can set it directly in [hotspot=1-6 file=1]`Dockerfile` with the `ENV` command. You can also set it in your [hotspot=1-88 file=0]`kubernetes.yaml` file by specifying a name and a value for the environment variable you want to set for a specific container. With these options in mind, you are going to use a ConfigMap and Secret to set these values. These are resources provided by Kubernetes that are used as a way to provide configuration values to your containers. A benefit is that they can be re-used across many different containers, even if they all require different environment variables to be set with the same value.

Create a ConfigMap to configure the greeting with the following `kubectl` command.
[role='command']
```
kubectl create configmap greeting-config --from-literal message=Greetings...
```

This command deploys a ConfigMap named `greeting-config` to your cluster. It has a key called `message` with a value of `Greetings...`. The `--from-literal` flag allows you to specify individual key-value pairs to store in this ConfigMap. Other available options, such as `--from-file` and `--from-env-file`, provide more versatility as to what you want to configure. Details about these options can be found in the https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-configmap-em-[{kube} CLI documentation].

Create a Secret to configure the credentials that `ping` will use to authenticate against `name` with the following `kubectl` command.
[role='command']
```
kubectl create secret generic name-credentials --from-literal username=bob --from-literal password=bobpwd
```
 
This command looks very similar to the command to create a ConfigMap, one difference is the word `generic`. It means that you're creating a Secret that is `generic`, in other words it stores information that is not specialized in any way. There are different types of secrets, such as secrets to store Docker credentials and secrets to store public/private key pairs.

A Secret is similar to a ConfigMap, except a Secret is used for confidential information such as credentials. One of the main differences is that you have to explicitly tell `kubectl` to show you the contents of a Secret. Additionally, when it does show you the information, it only shows you a Base64 encoded version so that a casual onlooker doesn't accidentally see any sensitive data. Secrets don't provide any encryption by default, that is something you'll either need to do yourself or find an alternate option to configure.

kubernetes.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/kubernetes.yaml[]
----

Dockerfile
[source, text, linenums, role='code_column']
----
include::finish/name/Dockerfile[]
----

== Updating {kube} resources

Next, you will update your {kube} deployments to set the environment variables in your containers based on the values configured in the ConfigMap and Secret created previously. 
The `env` sections under the `name-container` is where the `GREETING` environment variable will be set.

and `ping-container` containers are where the environment variables will be set.

[role="code_command hotspot=22-27", subs="quotes"]
----
Set the `GREETING` environment variable in the `kubernetes` file.
`kubernetes.yaml`
----

kubernetes.yaml
[source, yaml, linenums, role='code_column']
----
include::finish/kubernetes.yaml[]
----

The `env` sections under the `ping-container` is where the `USERNAME` and `PASSWORD` environment variables will be set.

[role="code_command hotspot=50-60", subs="quotes"]
----
Set the `USERNAME` and `PASSWORD` environment variables in the `kubernetes` file.
`kubernetes.yaml`
----


In the `kubernetes.yaml` file where the containers are defined, you can see the [hotspot=24]`valueFrom` field which allows you to specify the value of an environment variable from a variety of sources. These sources include a ConfigMap, a Secret, and information about the cluster. In this example [hotspot=25]`configMapKeyRef` gets the value `message` from the ConfigMap [hotspot=26]`greeting-config`. Similarly, [hotspot=53]`secretKeyRef` gets the values `username` and `password` from the Secret `name-credentials`.

== Deploying your changes

Rebuild the application using `mvn package`.
[role='command']
```
mvn package
```

Run the following commands to deploy your changes to the {kube} cluster.
[role='command']
```
kubectl delete -f kubernetes.yaml
kubectl apply -f kubernetes.yaml
```

Navigate to `{name-api}` and you will see that the greeting message has changed from `Hello!` to `Greetings...`. Verify that `{ping-api}/name-service` is working as intended. If it is not, then check the configuration of the credentials.

== Testing the microservices

****
[system]#*{win} | {mac}*#

Run the integration tests against a cluster running with a hostname of localhost:
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=localhost -Dname.message=Greetings...
```

[system]#*{linux}*#

Run the integration tests against a cluster running at Minikube's IP address:
[role='command']
```
mvn verify -Ddockerfile.skip=true -Dcluster.ip=`minikube ip` -Dname.message=Greetings...
```
****


The tests check that the `name` service responds with a container name and that the message in the response matches the configured message. The tests for `ping` verify that the service returns with a `pong` response on success and that it gracefully handles a bad response. If the credentials are misconfigured, then the `ping` test will fail, so the `ping` test indirectly verifies the credentials are correctly configured.

After the tests succeed, you should see output similar to the following in your console.

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.name.NameEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.542 sec - in it.io.openliberty.guides.name.NameEndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.ping.PingEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.761 sec - in it.io.openliberty.guides.ping.PingEndpointTest

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

== Tearing down the {kube} resources

Run the following commands to delete all the resources that you created.
[role='command']
```
kubectl delete -f kubernetes.yaml
kubectl delete configmap greeting-config
kubectl delete secret name-credentials
```

// =================================================================================================
// finish
// =================================================================================================

== Great work! You're done!

You have used MicroProfile Config to externalize the configuration of two microservices, and then you configured them by creating a ConfigMap and Secret in your {kube} cluster.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]