apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deployment
  labels:
    app: name
spec:
  selector:
    matchLabels:
      app: name
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
      - name: name-container
        image: name:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        # Set the GREETING environment variable
        env:
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: greeting-config
              key: message
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  labels:
    app: ping
spec:
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping-container
        image: ping:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
        # Set the PING_USERNAME and PING_PASSWORD environment variables
        env:
        - name: PING_USERNAME
          valueFrom:
            secretKeyRef:
              name: name-credentials
              key: username
        - name: PING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: name-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: name-service
spec:
  type: NodePort
  selector:
    app: name
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
spec:
  type: NodePort
  selector:
    app: ping
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32000
